repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: end-of-file-fixer

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml|yamllint)$

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v26.1.1
    hooks:
      - id: ansible-lint
        files: ^(?!\.).*\.(yaml|yml)$
        verbose: true
        args: ["-p", "./"]
