---
- name: Install ArgoCD
  hosts: label_kubernetes_role_control_plane
  vars_files:
    - ./vars.yml
  remote_user: "{{ ssh_user }}"
  become: true
  run_once: true
  roles:
    - role: argocd
      vars:
        argocd__chart_version: "{{ argocd_chart_version }}"
        argocd__install_cli: true
        argocd__helm_values: "{{ argocd_helm_values | from_yaml }}"
