apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/wittdennis/argocd-setup
    - https://github.com/wittdennis/k8s-platform
  destinations:
    - namespace: "argocd"
      server: {{ .Values.destination.server }}
  clusterResourceWhitelist:
    - group: ""
      kind: "argoproj.io:Application"
    - group: ""
      kind: "argoproj.io:ApplicationSet"
  namespaceResourceWhitelist:
    - group: ""
      kind: "argoproj.io:Application"
    - group: ""
      kind: "argoproj.io:ApplicationSet"
