apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argocd
  syncPolicy:
    automated: {}
  destination:
    namespace: argocd
    server: {{ .Values.destination.server }}
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 6.6.0
    chart: argo/argo-cd
    helm:
      releaseName: argocd
      values: |

        global:
          domain: k8s.home
        securityContext:
          fsGroup: 1000
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        networkPolicy:
          create: true
        server:
          ingress:
            enabled: false
        configs:
          params:
            server.insecure: true
            server.rootpath: /argocd
            server.basehref: /argocd
