apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argocd
  syncPolicy:
    automated: {}
  destination:
    namespace: argocd
    server: {{ .Values.destination.server }}
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 6.7.3
    chart: argo-cd
    helm:
      releaseName: argocd
      values: |

        global:
          domain: deployments.home.derwitt.net
        securityContext:
          fsGroup: 1000
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        networkPolicy:
          create: true
        server:
          ingress:
            enabled: false
        configs:
          cm:
            # ignore auto converted resources from victoria metrics operator
            resource.exclusions: |
              - apiGroups:
                  - "operator.victoriametrics.com"
                kinds:
                  - "VMServiceScrape"
                clusters:
                  - {{ .Values.destination.server }}
          params:
            server.insecure: true
