---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: deployments-home-derwitt-net-cert
  namespace: argocd
spec:
  secretName: deployments-home-derwitt-net-cert
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - deployments.home.derwitt.net
