---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-secrets
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: dex-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /argocd-dex
        property: microsoft-application-id
      secretKey: microsoft-application-id
    - remoteRef:
        conversionStrategy: Default
        key: /argocd-dex
        property: microsoft-client-secret
      secretKey: microsoft-client-secret
    - remoteRef:
        conversionStrategy: Default
        key: /argocd-dex
        property: microsoft-tenant-id
      secretKey: microsoft-tenant-id
