apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foundry
  namespace: foundry
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: foundry
  syncPolicy:
    automated:
      prune: true
  destination:
    namespace: foundry
    server: {{ .Values.destination.server }}
  source:
    path: "."
    repoURL: https://github.com/wittdennis/foundryvtt-management
    targetRevision: HEAD
    directory:
      exclude: "*.json"
