apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: app-of-apps
  syncPolicy:
    automated:
      prune: true
  destination: 
    namespace: argocd
    server: {{ .Values.destination.server }}
  source:
    path: packages/argo-apps
    repoURL: https://github.com/wittdennis/k8s-platform    
    targetRevision: HEAD