---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-platform
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/wittdennis/k8s-platform
    - https://argoproj.github.io/argo-helm
    - https://runatlantis.github.io/helm-charts
    - https://charts.jetstack.io
    - https://charts.dexidp.io
    - https://charts.external-secrets.io
    - https://helm.releases.hashicorp.com
    - https://kubernetes.github.io/ingress-nginx
    - https://oauth2-proxy.github.io/manifests
    - https://prometheus-community.github.io/helm-charts
    - https://robusta-charts.storage.googleapis.com
    - https://victoriametrics.github.io/helm-charts
    - https://operator.min.io
    - https://charts.longhorn.io
    - https://kubernetes-sigs.github.io/external-dns/
    - https://grafana.github.io/helm-charts
    - https://kubernetes-sigs.github.io/descheduler
    - https://charts.releases.teleport.dev
    - https://chartmuseum.github.io/charts
    - https://charts.derwitt.dev
    - https://cowboysysop.github.io/charts/
    - https://helm.cilium.io
    - oci://ghcr.io/siderolabs/charts/talos-cloud-controller-manager
  sourceNamespaces:
    - argocd
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
