apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-platform
  syncPolicy:
    automated: {}
  destination: 
    namespace: argocd
    server: {{ .Values.destination.server }}
  source:
    path: appsets
    repoURL: https://github.com/wittdennis/k8s-platform    
    targetRevision: HEAD