---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mogenius-ghcr
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: mogenius-ghcr
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: helm
        url: ghcr.io/mogenius/helm-charts
        enableOCI: "true"
        username: pat
  data:
    - remoteRef:
        conversionStrategy: Default
        key: argocd/mogenius-ghcr-token
        property: token
      secretKey: password
