---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: oidc-secret
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /argocd/oidc
        property: authentik-client-secret
      secretKey: oidc.authentik.client-secret
