---
apiVersion: v1
kind: Secret
metadata:
  name: yggdrasil
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://git.derwitt.site/homelab/yggdrasil.git
