---
argocd_version: v3.3.3 # renovate: datasource=github-releases depName=argoproj/argo-cd versioning=semver
argocd_chart_version: 9.4.9 # renovate: datasource=github-releases depName=argoproj/argo-helm extractVersion=^argo-cd-(?<version>.*)$ versioning=semver
argocd_helm_values: {}
argocd_install_cli: false
argocd_action: deploy
