---
- name: Install ArgoCD
  hosts: localhost
  vars_files:
    - ./vars.yml
  run_once: true
  roles:
    - role: argocd
      vars:
        argocd_helm_values: "{{ argocd_helm_values | from_yaml }}"
        argocd_action: "deploy"
