---
ssh_user: dwitt

argocd_chart_version: 6.6.0
argocd_helm_values:
  global:
    domain: deployments.home.derwitt.net
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  networkPolicy:
    create: true
  server:
    ingress:
      enabled: false
  configs:
    params:
      server.insecure: true
