---
- name: ARGOCD | Add argocd helm repo
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: ARGOCD | Deploy argocd
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true
    chart_version: "{{ argocd__chart_version }}"
    values: "{{ argocd__helm_values }}"
