---
- name: Install argo-cd cli
  when: argocd_install_cli and argocd_action == "deploy"
  ansible.builtin.include_tasks:
    file: install-cli.yml

- name: Deploy argo-cd
  when: argocd_action == "deploy"
  ansible.builtin.include_tasks:
    file: deploy.yml

- name: Remove argo-cd
  when: argocd_action == "remove"
  ansible.builtin.include_tasks:
    file: remove.yml
