---
- name: ARGOCD | Install argo-cd cli
  when: argocd__install_cli and argocd__action == "deploy"
  ansible.builtin.include_tasks:
    file: install-cli.yml

- name: ARGOCD | Deploy argo-cd
  when: argocd__action == "deploy"
  ansible.builtin.include_tasks:
    file: deploy.yml

- name: ARGOCD | Remove argo-cd
  when: argocd__action == "remove"
  ansible.builtin.include_tasks:
    file: remove.yml
