name: lint

on: [push]

jobs:
  ansible-lint:
    uses: wittdennis/pipelines/.github/workflows/ansible-lint.yaml@aa83050fcb03fe69f7bff031a5452f387d19aa23 # 2.0.20
    with:
      requirements-file: ansible/requirements.yml

  yaml-lint:
    uses: wittdennis/pipelines/.github/workflows/yaml-lint.yaml@aa83050fcb03fe69f7bff031a5452f387d19aa23 # 2.0.20
    with:
      yamllint-path: .yamllint
