name: lint

on: [push]

jobs:
  ansible-lint:
    uses: wittdennis/pipelines/.github/workflows/ansible-lint.yaml@1d8d497ce041021d980ccca647133a342d8290bb # 2.0.49
    with:
      requirements-file: ansible/requirements.yml

  yaml-lint:
    uses: wittdennis/pipelines/.github/workflows/yaml-lint.yaml@1d8d497ce041021d980ccca647133a342d8290bb # 2.0.49
    with:
      yamllint-path: .yamllint
